services:
  - type: web
    name: telegram-card-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python card.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
